package com.jsjlzj.wayne.data.db;


import com.jsjlzj.wayne.entity.dao.MdlAddressItem;
import com.jsjlzj.wayne.entity.dao.MdlRole;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mdlAddressItemDaoConfig;
    private final DaoConfig mdlRoleDaoConfig;

    private final MdlAddressItemDao mdlAddressItemDao;
    private final MdlRoleDao mdlRoleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mdlAddressItemDaoConfig = daoConfigMap.get(MdlAddressItemDao.class).clone();
        mdlAddressItemDaoConfig.initIdentityScope(type);

        mdlRoleDaoConfig = daoConfigMap.get(MdlRoleDao.class).clone();
        mdlRoleDaoConfig.initIdentityScope(type);

        mdlAddressItemDao = new MdlAddressItemDao(mdlAddressItemDaoConfig, this);
        mdlRoleDao = new MdlRoleDao(mdlRoleDaoConfig, this);

        registerDao(MdlAddressItem.class, mdlAddressItemDao);
        registerDao(MdlRole.class, mdlRoleDao);
    }
    
    public void clear() {
        mdlAddressItemDaoConfig.clearIdentityScope();
        mdlRoleDaoConfig.clearIdentityScope();
    }

    public MdlAddressItemDao getMdlAddressItemDao() {
        return mdlAddressItemDao;
    }

    public MdlRoleDao getMdlRoleDao() {
        return mdlRoleDao;
    }

}
